name: Spellcheck
on: 
  push:
    paths:
    - '**.sh'
  pull_request:
    paths:
    - '**.sh'

jobs:
  lint:
    name: shellcheck for shell files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: shellcheck files
      uses: ludeeus/action-shellcheck@master