name: Test script
on: [ push, pull_request]

jobs:
  lint:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck files
      uses: ludeeus/action-shellcheck@master

  dump:
    name: dump mysqldb
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: dump
      run: |
        echo "MYSQL_DATABASE=$(date | md5sum|head -c16)" > .env
        echo "MYSQL_USER=$(date | md5sum|head -c16)" >> .env
        echo "MYSQL_PASSWORD=$(date | md5sum|head -c16)" >> .env
        echo "MYSQL_RANDOM_ROOT_PASSWORD=true" >> .env
        docker run --name dbaseorig --rm -d --env-file=.env mariadb:10.4
        sleep 30
        docker exec --env-file=.env dbaseorig /bin/bash -c 'mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} -e "create table tbl(name varchar(20),age int); insert into tbl(name,age) values (\"bob\", 25);"'
        ./docker-mysqldump.sh
        docker stop dbaseorig
    - name: upload dbase
      uses: actions/upload-artifact@v2
      with:
        name: sqldump
        path: "*.gz"
   
  test:
    name: import and test mysqldb
    runs-on: ubuntu-latest
    needs: dump
    services:
      mariadb:
        image: mariadb:10.4
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: true
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: dbasetest
        ports:
          - 3306
        volumes:
          - initsql:/docker-entrypoint-initdb.d
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: sqldump
        path: initsql

    - name: test
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        mysql -u test -ptest -h 127.0.0.1 -P "${PORT}" dbasetest -e "select * from tbl"
